name: EAS Build iOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.OrionTV }} # ✅ 设置在这里，全局可用

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      # ❌ 删除 Login to EAS 步骤

      - name: Trigger EAS Build
        run: eas build --platform ios --profile production --non-interactive
